aca_shop_homepage:
    path: /
    defaults: { _controller: AcaShopBundle:Default:homepage }

aca_login_handler:
    path: /login
    defaults: { _controller: AcaShopBundle:Login:login }
    methods: [GET, POST]

aca_logout_handler:
    path: /logout
    defaults: { _controller: AcaShopBundle:Login:logout }
    methods: [POST]

aca_register:
    path: /register
    defaults: { _controller: AcaShopBundle:Login:register }
    methods: [GET]

aca_add_account:
    path: /register/new_user
    defaults: { _controller: AcaShopBundle:Login:addAccount }
    methods: [POST]

aca_show_products:
    path: /products
    defaults: { _controller: AcaShopBundle:Product:showAllProducts }
    methods: [GET]

aca_show_product_detail:
    path: /products/detail/{slug}
    defaults: { _controller: AcaShopBundle:Product:showProduct }
    methods: [GET]

aca_show_cart:
    path: /cart
    defaults: { _controller: AcaShopBundle:Cart:showCart }
    methods: [GET]

aca_add_to_cart:
    path: /add_to_cart
    defaults: { _controller: AcaShopBundle:Cart:addToCart }
    methods: [POST]